language: c
sudo: false

cache:
  directories:
    - $HOME/.cabsnap
    - $HOME/.stack

matrix:
  include:
    - env: STACK_YAML=stack-800.yaml
      compiler: ": #GHC 8.0.2"
    - env: STACK_YAML=stack-802.yaml
      compiler: ": #GHC 8.2.1"
    - env: STACK_YAML=stack-804.yaml
      compiler: ": #GHC 8.4.3"
    - env: STACK_YAML=stack-806.yaml
      compiler: ": #GHC 8.6.1"
    - env: STACK_YAML=stack-808.yaml
      compiler: ": #GHC 8.8.2"
  allow_failures:
    - env: STACK_YAML=stack-808.yaml

before_install:
 # install Stack
 - mkdir -p ~/.local/bin
 - export PATH=$HOME/.local/bin:$PATH
 - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
 - unset CC
 - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH

install:
 - stack --version
 - |
  stack build --no-terminal --only-dependencies \
    --flag ghc-typelits-presburger:examples \
    --flag ghc-typelits-presburger-core:examples

# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
script:
 - |
  stack --no-terminal --skip-ghc-check test \
      --flag ghc-typelits-presburger:examples \
      --flag ghc-typelits-presburger-core:examples

# Check that the resulting source distribution can be built & installed.
# If there are no other `.tar.gz` files in `dist`, this can be even simpler:
# `cabal install --force-reinstalls dist/*-*.tar.gz`
# EOF
